'use client';

import type { SongInfo } from '@/types';
import type { ColumnDef } from '@tanstack/react-table';

export const columns: ColumnDef<SongInfo>[] = [
  { accessorKey: 'name', header: '曲名' },
  { accessorKey: 'count', header: '回数' },
  { accessorKey: 'rsgTokyo', header: 'RSG東京' },
  { accessorKey: 'bcAichi', header: 'BC愛知' },
  { accessorKey: 'bcIshikawa', header: 'BC石川' },
  { accessorKey: 'bcHyogo', header: 'BC兵庫' },
  { accessorKey: 'bcChiba', header: 'BC千葉' },
  { accessorKey: 'ctrOsaka', header: 'CtR大阪' },
  { accessorKey: 'ctrAichi', header: 'CtR愛知' },
  { accessorKey: 'ctrTokyo1', header: 'CtR東京1日目' },
  { accessorKey: 'ctrTokyo2', header: 'CtR東京2日目' },
  { accessorKey: 'sw', header: 'SW' },
  { accessorKey: 'hhOsaka', header: 'HH大阪' },
  { accessorKey: 'hhAichi', header: 'HH愛知' },
  { accessorKey: 'hhFukuoka', header: 'HH福岡' },
  { accessorKey: 'hhMiyagi', header: 'HH宮城' },
  { accessorKey: 'hhKanagawa', header: 'HH神奈川' },
  { accessorKey: 'glowAichi', header: 'glow愛知' },
  { accessorKey: 'glowMiyagi', header: 'glow宮城' },
  { accessorKey: 'glowFukuoka', header: 'glow福岡' },
  { accessorKey: 'glowKanagawa', header: 'glow神奈川' },
  { accessorKey: 'glowHyogo', header: 'glow兵庫' },
  { accessorKey: 'saHyogo', header: 'SA兵庫' },
  { accessorKey: 'saMiyagi', header: 'SA宮城' },
  { accessorKey: 'saAichi', header: 'SA愛知' },
  { accessorKey: 'saFukuoka', header: 'SA福岡' },
  { accessorKey: 'saKanagawa1', header: 'SA神奈川1日目' },
  { accessorKey: 'saKanagawa2', header: 'SA神奈川2日目' },
  { accessorKey: 'hbHyogo', header: 'HB兵庫' },
  { accessorKey: 'hbHiroshima', header: 'HB広島' },
  { accessorKey: 'hbAichi', header: 'HB愛知' },
  { accessorKey: 'hbFukuoka', header: 'HB福岡' },
  { accessorKey: 'hbHokkaido', header: 'HB北海道' },
  { accessorKey: 'hbChiba1', header: 'HB千葉1日目' },
  { accessorKey: 'hbChiba2', header: 'HB千葉2日目' },
  { accessorKey: 'chomin2018TokyoDay', header: '町民18東京昼' },
  { accessorKey: 'chomin2018TokyoNight', header: '町民18東京夜' },
  { accessorKey: 'chomin2019HyogoDay', header: '町民19兵庫昼' },
  { accessorKey: 'chomin2019HyogoNight', header: '町民19兵庫夜' },
  { accessorKey: 'chomin2019TokyoDay', header: '町民19東京昼' },
  { accessorKey: 'chomin2019TokyoNight', header: '町民19東京夜' },
  { accessorKey: 'chomin2021YokohamaDay', header: '町民21横浜昼' },
  { accessorKey: 'chomin2021YokohamaNight', header: '町民21横浜夜' },
  { accessorKey: 'chomin2023TokyoDay', header: '町民23東京昼' },
  { accessorKey: 'chomin2023TokyoNight', header: '町民23東京夜' },
  { accessorKey: 'chomin2024SaitamaDay', header: '町民24埼玉昼' },
  { accessorKey: 'chomin2024SaitamaNight', header: '町民24埼玉夜' },
  { accessorKey: 'chomin2024Shiga', header: '町民24滋賀' },
  { accessorKey: 'chomin2024Aichi', header: '町民24愛知' },
];
