import './globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'inori-track',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='ja'>
      <body className='container mx-auto bg-cyan-500 text-slate-50'>
        <main className='flex flex-col items-center min-h-screen py-10'>
          <div className='space-y-4 w-80 md:w-full max-w-2xl'>{children}</div>
        </main>
      </body>
    </html>
  );
}
